fill out some blanks
fluxcd/fluxcd.io pull request #28
Opened 2020-10-28 16:31 UTC by dholbach

cc @hiddeco

2020-10-28 16:33 UTC, hiddeco approved these changes

2020-10-28 16:35 UTC, hiddeco requested changes

2020-10-28 16:35 UTC, hiddeco commented on config.toml
> +url         = "#https://www.youtube.com/watch?v=0v5bjysXTL8"
```suggestion
url         = "https://www.youtube.com/watch?v=0v5bjysXTL8"
```

2020-10-30 13:24 UTC, hiddeco commented on config.toml
> +url         = "https://www.youtube.com/watch?v=8v94nUkXsxU"
```suggestion
title       = " Introduction To GitOps and GitOps Toolkit"
description = """
<some description>
"""
url         = "https://www.youtube.com/watch?v=qQBtSkgl7tI"
```

Looking back, this is a better introduction than the deep dive we did on KubeCon where we tried to include too much information in 40 minutes.

2020-10-30 13:32 UTC, hiddeco approved these changes
Thank you @dholbach :bouquet:

2020-10-30 13:32 UTC, merged

2020-10-30 13:32 UTC, dholbach commented
:small_airplane: